
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Mar 14 23:12:43 CST 2016
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym1 {
  /* terminals */
  public static final int RMate = 47;
  public static final int Rq = 6;
  public static final int parentesisIzq = 11;
  public static final int RTelefonoC = 39;
  public static final int RCons = 46;
  public static final int RTelefonoA = 38;
  public static final int RAnd = 49;
  public static final int RNombre = 45;
  public static final int coma = 9;
  public static final int igual = 8;
  public static final int corcheteIzq = 15;
  public static final int menosmenos = 22;
  public static final int puntoycoma = 10;
  public static final int numero = 52;
  public static final int masmas = 21;
  public static final int RNombreC = 35;
  public static final int RNombreA = 34;
  public static final int menos = 3;
  public static final int menor = 18;
  public static final int RRequestC = 24;
  public static final int RDireccionC = 43;
  public static final int EOF = 0;
  public static final int llaveIzq = 13;
  public static final int RApellidoC = 37;
  public static final int parentesisDer = 12;
  public static final int RRequestA = 23;
  public static final int RDireccionA = 42;
  public static final int mas = 2;
  public static final int ROr = 50;
  public static final int RApellidoA = 36;
  public static final int error = 1;
  public static final int tstring = 53;
  public static final int mayor = 17;
  public static final int menorigual = 20;
  public static final int por = 4;
  public static final int corcheteDer = 16;
  public static final int id = 55;
  public static final int REmailC = 41;
  public static final int REmailA = 40;
  public static final int Ptn = 7;
  public static final int mayorigual = 19;
  public static final int RPasswordC = 30;
  public static final int RPasswordA = 29;
  public static final int RExtension = 31;
  public static final int dolar = 44;
  public static final int RInicioUC = 26;
  public static final int RPalabraIdC = 28;
  public static final int RInicioUA = 25;
  public static final int RPalabraIdA = 27;
  public static final int div = 5;
  public static final int llaveDer = 14;
  public static final int RCrearUC = 33;
  public static final int RIgualIgual = 51;
  public static final int RCrearUA = 32;
  public static final int RMateC = 48;
  public static final int tchar = 54;
}

